language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository ppa:ubuntu-lxc/daily -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfuse-dev libdbus-glib-1-dev libglib2.0-dev coreutils cgmanager
script: ./bootstrap.sh && ./configure && make -j4 && make tests && sudo ./tests/main.sh
notifications:
  email:
    recipients:
      - serge.hallyn@ubuntu.com
