dist: bionic
sudo: required
language: c

compiler:
 - gcc
 - clang

arch:
 - amd64
 - arm64
 - ppc64le
 - s390x

env:
  global:
   - secure: "Nu2cNo2RHjZxl2eiuWVRlznMAZu4YCvsbaxf4djolj+MYIw2KfMqMM9cM9EC3/ikljZcrlleOXZDcyNFdlNIbeadXythleNQJRK3eX8x226f6vqAs4i/ppbl4oMnlQx3yzG9+PBHtelv/db8TxXLX51+qB8N0820v0ieTpwYbkI="

addons:
  coverity_scan:
    project:
      name: "lxc/lxcfs"
      description: "FUSE filesystem for LXC https://linuxcontainers.org/lxcfs"
    build_command_prepend: "./bootstrap.sh && ./configure"
    build_command: "make -j4"
    branch_pattern: master

before_install:
 - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

 - sudo apt-get update -qq
 - sudo apt-get -y install -qq automake coreutils libfuse-dev libtool

script:
 - ./bootstrap.sh
 - ./configure --prefix=/usr
 - make -j4
 - (cd tests && make tests)
 - echo 1 | sudo tee /sys/fs/cgroup/cpuset/cgroup.clone_children || true
 - sudo -E tests/main.sh

notifications:
  email:
    recipients:
      - serge.hallyn@ubuntu.com
      - stgraber@ubuntu.com
